version: '3'

services:
  mycompany.visitors.web:
    image: mycompany.visitors.web
    build:
      context: .\MyCompany.Visitors.Web
      dockerfile: Dockerfile

  mycompany.visitors.crmsvc:
    image: mycompany.visitors.crmsvc
    build:
      context: ./MyCompany.Visitors.CRMSvc
      dockerfile: Dockerfile
