version: '3'

services:
  mycompany.visitors.web:
    image: mycompany.visitors.web:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - .\MyCompany.Visitors.Web:C:\inetpub\wwwroot
      - ${VS_REMOTE_DEBUGGER_PATH}:C:\remote_debugger:ro
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"

  mycompany.visitors.crmsvc:
    image: mycompany.visitors.crmsvc:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
    volumes:
      - ./MyCompany.Visitors.CRMSvc:C:\app
      - ${NUGET_PACKAGES}:C:\.nuget\packages:ro
      - ${VS_REMOTE_DEBUGGER_ONECORE_PATH}:C:\remote_debugger:ro
    entrypoint: powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
      - "com.microsoft.visualstudio.targetframework=dotnetcore"
  sql:
    image: microsoft/mssql-server-windows
    environment:
      SA_PASSWORD: "P@ssw0rd1"
      ACCEPT_EULA: "Y"
    ports:
      - "1443:1443"

      #attach_dbs: "[{'dbName':'visitors','dbFiles':['C:\\temp\\visitors.mdf','C:\\temp\\visitors_log.ldf']}]"
