version: '3'

services:
  mycompany.visitors.web:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ${VS_REMOTE_DEBUGGER_PATH}:C:\remote_debugger:ro
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"

  mycompany.visitors.crmsvc:
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - ${VS_REMOTE_DEBUGGER_ONECORE_PATH}:C:\remote_debugger:ro
    entrypoint: powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=windows"
      - "com.microsoft.visualstudio.targetframework=dotnetcore"
